<?php

/**
 * @file
 * Module file for mypagermini.
 */

use Drupal\Core\Template\Attribute;
use Drupal\Core\Render\Markup;
use Drupal\Core\Url;

/**
 * Implements hook_preprocess_mypagermini_pager().
 */
function template_preprocess_mypagermini_pager(&$variables) {
  global $pager_page_array, $pager_total, $pager_total_items, $pager_limits;

  /* @var $pager_manager \Drupal\Core\Pager\PagerManagerInterface */
  $pager_manager = \Drupal::service('pager.manager');

  $tags = &$variables['tags'];
  $element = $variables['element'];
  $parameters = $variables['parameters'];

  // Current is the page we are currently paged to.
  $variables['items']['current'] = $pager_page_array[$element] + 1;

  if ($pager_total[$element] > 1 && $pager_page_array[$element] > 0) {
    $options = [
      'query' => $pager_manager->getUpdatedParameters($parameters, $element, $pager_page_array[$element] - 1),
    ];
    $variables['items']['previous']['href'] = Url::fromRoute('<current>', [], $options);
    if (isset($tags[1])) {
      $variables['items']['previous']['text'] = $tags[1];
    }
    $variables['items']['previous']['attributes'] = new Attribute();
  }
  else {
    $variables['items']['previous']['href'] = Url::fromRoute('<current>');
    if (isset($tags[1])) {
      $variables['items']['previous']['text'] = $tags[1];
    }
    $variables['items']['previous']['attributes'] = new Attribute([
      'disabled' => TRUE,
      'class' => ['disabled'],
      'rel' => 'prev'
    ]);
  }


  if ($pager_page_array[$element] < ($pager_total[$element] - 1)) {
    $options = [
      'query' => $pager_manager->getUpdatedParameters($parameters, $element, $pager_page_array[$element] + 1),
    ];
    $variables['items']['next']['href'] = Url::fromRoute('<current>', [], $options);
    if (isset($tags[3])) {
      $variables['items']['next']['text'] = $tags[3];
    }
    $variables['items']['next']['attributes'] = new Attribute();
  }
  else {
    $variables['items']['next']['href'] = Url::fromRoute('<current>');
    if (isset($tags[3])) {
      $variables['items']['next']['text'] = $tags[3];
    }
    $variables['items']['next']['attributes'] = new Attribute([
      'disabled' => TRUE,
      'class' => ['disabled'],
      'rel' => 'next'
    ]);
  }

  // Add nofollow to links
  if ($variables['options']['nofollow'] && !$variables['options']['is_not_link']) {
    if ($variables['items']['previous']) {
      /* @var \Drupal\Core\Template\Attribute $attributes */
      $attributes = $variables['items']['previous']['attributes'];
      $attributes->setAttribute('rel', 'nofollow');
    }
    if ($variables['items']['next']) {
      /* @var \Drupal\Core\Template\Attribute $attributes */
      $attributes = $variables['items']['next']['attributes'];
      $attributes->setAttribute('rel', 'nofollow');
    }
  }

  // Add class link (.link is required for is_not_link)
  if ($variables['items']['previous']) {
    /* @var \Drupal\Core\Template\Attribute $attributes */
    $attributes = $variables['items']['previous']['attributes'];
    $attributes->addClass('link');
  }
  if ($variables['items']['next']) {
    /* @var \Drupal\Core\Template\Attribute $attributes */
    $attributes = $variables['items']['next']['attributes'];
    $attributes->addClass('link');
  }

  // html_tag
  $html_tag = 'a';
  if ($variables['options']['is_not_link']) {
    $html_tag = 'div';
  }
  if ($variables['items']['previous']) {
    $variables['items']['previous']['html_tag'] = $html_tag;
  }
  if ($variables['items']['next']) {
    $variables['items']['next']['html_tag'] = $html_tag;
  }


  // This is based on the entire current query string. We need to ensure
  // cacheability is affected accordingly.
  $variables['#cache']['contexts'][] = 'url.query_args';

  $total_items = $pager_total_items[$element];
  $items_per_page = $pager_limits[$element];
  $current = $pager_page_array[$element] + 1;
  $current_items = $current * $items_per_page;
  if ($current_items > $total_items) {
    $current_items = $total_items;
  }

  $search_replace = [
    '@current_items' => $current_items,
    '@total_items' => $total_items,
    '@current' => $current,
  ];

  if (!empty($variables['options']['pager_title'])) {
    $pager_title = $variables['options']['pager_title'];
    $pager_title = str_replace(array_keys($search_replace), array_values($search_replace), $pager_title);
    $variables['pager_title'] = Markup::create($pager_title);
  }

  if (!empty($variables['options']['pager_subtitle'])) {
    $pager_subtitle = $variables['options']['pager_subtitle'];
    $pager_subtitle = str_replace(array_keys($search_replace), array_values($search_replace), $pager_subtitle);
    $variables['pager_subtitle'] = Markup::create($pager_subtitle);
  }

}



